"""Gate 0G: embed OpenUSD's plugin resources (plugInfo.json and whatever
the plugins' resources/ dirs hold that a stage read needs:
generatedSchema.usda) as a C array, so the guest never opens a file.

  python gen_resources.py <usd build dir> <out .inc>

The resources are taken from the build tree's configured copies
(<build>/pxr/.../<lib>/plugInfo.json after @PLUG_INFO_*@ substitution) and
exposed at the install layout's paths, /usd/<lib>/resources/<file>, so the
plugInfo's Root ".." and ResourcePath "resources" resolve inside the table.
"""
import os, sys

build, out = sys.argv[1], sys.argv[2]
LIBS = ["ar", "sdf", "sdr", "usd", "usdGeom", "usdSkel", "usdShade"]
EXTRA = ["generatedSchema.usda"]

entries = []
for dirpath, _, files in os.walk(os.path.join(build, "pxr")):
    lib = os.path.basename(dirpath)
    if lib not in LIBS or "CMakeFiles" in dirpath:
        continue
    for f in files:
        if f == "plugInfo.json" or f in EXTRA:
            entries.append((f"/usd/{lib}/resources/{f}", os.path.join(dirpath, f)))

src_root = os.environ.get("USD_SRC")
# generatedSchema.usda is not configured, only copied at install; fall back to
# the source tree when the build dir has none.
have = {p for p, _ in entries}
if src_root:
    for dirpath, _, files in os.walk(os.path.join(src_root, "pxr", "usd")):
        lib = os.path.basename(dirpath)
        if lib in LIBS and "generatedSchema.usda" in files:
            p = f"/usd/{lib}/resources/generatedSchema.usda"
            if p not in have:
                entries.append((p, os.path.join(dirpath, "generatedSchema.usda")))

entries.sort()
with open(out, "w", newline="\n") as o:
    o.write("// generated by gates/0g-openusd/gen_resources.py -- do not edit\n")
    total = 0
    for i, (p, src) in enumerate(entries):
        data = open(src, "rb").read()
        total += len(data)
        o.write(f"static const char kRes{i}[] =\n")
        for k in range(0, len(data), 64):
            chunk = "".join(f"\\x{b:02x}" for b in data[k:k + 64])
            o.write(f'\t"{chunk}"\n')
        o.write(";\n")
    o.write("static const UsdProbeResource kUsdResources[] = {\n")
    for i, (p, _) in enumerate(entries):
        o.write(f'\t{{"{p}", kRes{i}, sizeof(kRes{i}) - 1}},\n')
    o.write("};\n")
print(f"{len(entries)} resources, {total} bytes -> {out}")
for p, s in entries:
    print("  ", p, "<-", s)
